### ISSUE TITLE
Value "data["1"].ArrowFunctionExpression" has additional properties.

### ISSUE THREAD

**Issue by Imarok** [jrsearles/eslint-plugin-brace-rules#1]
I'd like to use your plugin to enforce allman brace style, but ignore arrow functions, but I can't get the config right (or your plugin doesn't work correctly).

This is my config:
```
{
    "parserOptions": {
        "ecmaVersion": 6
    },
    "plugins": [
        "brace-rules"
    ],
    "rules": {
        "brace-rules/brace-on-same-line": ["warn", "allman", { "ArrowFunctionExpression": "ignore" }]
    }
}
```
I'm getting this error when trying to execute eslint:
```
[object Object]:
	Configuration for rule "brace-rules/brace-on-same-line" is invalid:
	Value "data["1"].ArrowFunctionExpression" has additional properties.

Error: [object Object]:
	Configuration for rule "brace-rules/brace-on-same-line" is invalid:
	Value "data["1"].ArrowFunctionExpression" has additional properties.

    at validateRuleOptions (/usr/local/lib/node_modules/eslint/lib/config/config-validator.js:111:15)
    at /usr/local/lib/node_modules/eslint/lib/config/config-validator.js:151:9
    at Array.forEach (native)
    at validateRules (/usr/local/lib/node_modules/eslint/lib/config/config-validator.js:150:30)
    at Object.validate (/usr/local/lib/node_modules/eslint/lib/config/config-validator.js:201:5)
    at loadFromDisk (/usr/local/lib/node_modules/eslint/lib/config/config-file.js:549:19)
    at Object.load (/usr/local/lib/node_modules/eslint/lib/config/config-file.js:592:20)
    at Config.loadSpecificConfig (/usr/local/lib/node_modules/eslint/lib/config.js:139:46)
    at new Config (/usr/local/lib/node_modules/eslint/lib/config.js:101:14)
    at new CLIEngine (/usr/local/lib/node_modules/eslint/lib/cli-engine.js:427:23)
```
Thank you for any help.

**Comment by jrsearles** [comment]
I think this is how you would want it configured:

```json
  "plugins": [
    "brace-rules"
  ],
  "rules": {
    "brace-rules/brace-on-same-line": ["warn", {
      "FunctionDeclaration": "never",
      "FunctionExpression": "never",
      "ArrowFunctionExpression": "always",
      "IfStatement": "never",
      "TryStatement": "never",
      "CatchClause": "never",
      "DoWhileStatement": "never",
      "WhileStatement": "never",
      "ForStatement": "never",
      "ForInStatement": "never",
      "ForOfStatement": "never",
      "SwitchStatement": "never"
    }, { "allowSingleLine": true }]
  }
```

**Comment by Imarok** [comment]
Thank you for your fast reply, this is exactly the config I wanted ;)
(What about adding an example config to your docu?)
